module.exports = [
  "centrs",
  "Āgenskalns",
  "Aplokciems",
  "Beberbeķi",
  "Berģi",
  "Bieķēnsala",
  "Bieriņi",
  "Bolderāja",
  "Bukulti",
  "Čiekurkalns",
  "Dārzciems",
  "Daugavgrīva",
  "Dreiliņi",
  "Dzegužkalns (Dzirciems)",
  "Iļģuciems",
  "Imanta",
  "Jaunciems",
  "Jaunmīlgrāvis",
  "Jugla",
  "Katlakalns",
  "Ķengarags",
  "Ķīpsala",
  "Kleisti",
  "Klīversala",
  "Krasta r-ns",
  "Krēmeri",
  "Mangaļi",
  "Mangaļsala",
  "Maskavas priekšpilsēta",
  "Mežaparks",
  "Mežciems",
  "Pļavnieki",
  "Purvciems",
  "Šampēteris-Pleskodāle",
  "Sarkandaugava",
  "Šķirotava",
  "Stacija-Tirgus",
  "Teika",
  "Torņakalns",
  "Vecāķi",
  "Vecdaugava",
  "Vecmīlgrāvis",
  "Vecrīga",
  "Voleri",
  "Zasulauks",
  "Ziepniekkalns",
  "Zolitūde",
  "VEF",
  "Cits",
]

